### ISSUE TITLE
Wrong link in index.md

### ISSUE THREAD

**Issue by rwv37** [Sanglorian/orcus#1]
In index.md, one line is supposed to have two links to two different formats of "Death and Chaos". The first link is fine, but the second link is actually to "Blood and Chaos.pdf" (as opposed to "Death and Chaos.pdf"). That file doesn't actually exist, so GitHub gives an error when you click on the link.

**Comment by Sanglorian** [comment]
Thank you! Should be fixed when the GitHub Pages site next refreshes.
